/*
TRABAJO PRACTICO INTEGRADOR - PROGRAMACION II 
SCRIPT .sql CREACION BD "LogisticaEnvios" PARA TPI.
GRUPO N°: 177
INTEGRANTES: MARTIN GOMEZ - MATIAS EZEQUIEL GONZALEZ - FRANCO ESTEBAN HERRERA GONZALEZ - AGUSTIN MARIO NICOLAS LEPKA
TEMA: PEDIDO -> ENVIO
ARCHIVO: 01_esquema_Envio-Pedido.sql
 */

CREATE DATABASE IF NOT EXISTS LogisticaEnvios;
USE LogisticaEnvios;

CREATE TABLE Envio (
    id INT PRIMARY KEY AUTO_INCREMENT,
    eliminado BOOLEAN DEFAULT FALSE,
    tracking VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin UNIQUE,
    empresa ENUM('ANDREANI', 'OCA', 'CORREO_ARG') NOT NULL,
    tipo ENUM('ESTANDAR', 'EXPRESS') NOT NULL,
    costo DECIMAL(10,2),
    fechaDespacho DATE,
    fechaEstimada DATE,
    estado ENUM('EN_PREPARACION', 'EN_CAMINO', 'ENTREGADO') NOT NULL
);

CREATE TABLE Pedido (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    eliminado BOOLEAN DEFAULT FALSE,
    numero VARCHAR(20) NOT NULL UNIQUE,
    fecha DATE NOT NULL,
    clienteNombre VARCHAR(120) NOT NULL,
    total DECIMAL(12,2) NOT NULL CHECK (total >= 0),
    estado ENUM('NUEVO', 'FACTURADO', 'ENVIADO') NOT NULL,
    envio_id INT NOT NULL UNIQUE, -- <-- UNIQUE garantiza 1->1
    FOREIGN KEY (envio_id) REFERENCES Envio(id) ON DELETE CASCADE
);
